name: Run Autoclaim

on:
  workflow_dispatch:

concurrency:
  group: 'pythonC'  # 设置唯一的组ID
  cancel-in-progress: true 

jobs:
  Binance:
    runs-on: self-hosted
    continue-on-error: true
    if: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.15

      - name: Install dependencies
        run: |
          python3 -m venv venv
          ./venv/bin/pip3 install websocket-client requests

      - name: Run Python Nopixels
        run: |
          ./venv/bin/python3 12.py